version: '3'
services:
   web:
     build: .
     image: web:latest
     container_name: web_container
     
     ports:
      - 8000:8000
     
     command: python3 manage.py runserver 0.0.0.0:8000


