# Generated by Django 4.1.5 on 2023-01-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='grocery',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
