# Generated by Django 4.1.5 on 2023-01-18 10:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('ifsc_code', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='Credit', max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserBankdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], default='Savings', max_length=50)),
                ('account_no', models.CharField(max_length=20, unique=True)),
                ('balance_amount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_branch', to='modelapp.branch')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bankdetails', to=settings.AUTH_USER_MODEL)),
                ('transaction_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelapp.transactionhistory')),
            ],
        ),
    ]
