# Generated by Django 4.1.5 on 2023-01-20 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankdetails',
            name='account_no',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='balance_amount',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
