# Generated by Django 4.1.5 on 2023-01-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='bool',
            field=models.BooleanField(null=True),
        ),
    ]
