# Generated by Django 4.1.5 on 2023-01-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_alter_demo_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='bool',
            field=models.BooleanField(verbose_name='boolean field'),
        ),
    ]
