# Generated by Django 4.1.5 on 2023-01-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_alter_demo_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='bool',
            field=models.BooleanField(default=True, verbose_name='boolean field'),
        ),
    ]
