# Generated by Django 4.1.5 on 2023-01-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_demo_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='positive_integers',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demo',
            name='small_integers',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
