# Generated by Django 4.1.5 on 2023-01-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_demo_positive_integers_demo_small_integers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='small_integers',
        ),
        migrations.AddField(
            model_name='demo',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demo',
            name='bool',
            field=models.BooleanField(default=True, null=True, verbose_name='boolean field'),
        ),
    ]
