# Generated by Django 4.1.5 on 2023-01-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_remove_demo_small_integers_demo_slug_alter_demo_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
