# Generated by Django 4.1.5 on 2023-01-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_articlereactionchanged'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereactionchanged',
            name='user',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
