# Generated by Django 4.1.5 on 2023-01-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_articlereactionchanged_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleReactionChanged',
        ),
    ]
