# Generated by Django 4.1.5 on 2023-01-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_delete_articlereactionchanged'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleReactionChanged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('article_reaction', models.CharField(max_length=30)),
                ('changed', models.BooleanField(default=False)),
            ],
        ),
    ]
