# Generated by Django 4.1.5 on 2023-01-30 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_articlereactionchanged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.article'),
        ),
    ]
