# Generated by Django 4.1.5 on 2023-01-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_articlecomments_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereactionchanged',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.article'),
            preserve_default=False,
        ),
    ]
