FROM python

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY ./requirements.txt /app/requirements.txt 

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Copy the Django code
COPY . .



# Install PostgreSQL and create a database
RUN apt-get update && \
    apt-get install -y postgresql && \
    service postgresql start && \
    su - postgres -c "createuser -s root" && \
    su - root -c "createdb mydatabase"

# Set environment variables for the database
ENV POSTGRES_USER=root \
    POSTGRES_PASSWORD=secret \
    POSTGRES_HOST=db \
    POSTGRES_PORT=5432 \
    POSTGRES_DB=mydatabase

# Start the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
