version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
      DJANGO_SU_NAME: admin
      DJANGO_SU_PASSWORD: password123
      
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  web:
    tty: true
    build: .
    command:
     sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydatabase
      DJANGO_SU_NAME: admin
      DJANGO_SU_PASSWORD: password123


volumes:
  postgres_data:
