# Generated by Django 4.1.5 on 2023-01-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
    ]
